### PR TITLE
Bumps bosh-init release dependencies

### PR DESCRIPTION
**Pull request by ryanmoran**
- update bosh release to 256
- update bosh-aws-cpi release to 51

### CODE REVIEW

**Comment by Amit-PivotalLabs** [comment]
Thanks!  LGTM, but mind squashing?  FYI, we'll eventually start doing this automatically ([story](https://www.pivotaltracker.com/story/show/115989493)).

**Comment by ryanmoran** [comment]
Squashed!

**Comment by zankich** [comment]
@ryanmoran can you also please update the SHA1 for each release, thanks!

**Comment by ryanmoran** [comment]
@zankich should be good to go now.

**Comment by zankich** [comment]
Thanks! 🚴

**Pull request merged**
